#!/bin/bash
curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d "{\"ids\":[\"Titanic\",\"Life is Beautiful\"]}" http://127.0.0.1:8989/add?access_token=B8CF722F917D
echo
