#!/bin/bash
curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d "{\"ids\":[{\"name\":\"Titanic\", \"context\": 200 } , {\"name\": \"Life is Beautiful\", \"context\": { \"a\": \"b\"}}]}" http://127.0.0.1:8989/get?access_token=B8CF722F917D
echo
